apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://kontantstotte.intern.dev.nav.no
    - https://kontantstotte.ansatt.dev.nav.no
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - https://kontantstotte.ansatt.dev.nav.no/auth/openid/callback
      claims:
        groups:
          - id: "71f503a2-c28f-4394-a05a-8da263ceca4a"  # '0000-GA-Kontantstotte-Veileder' - Veileder
          - id: "c7e0b108-7ae6-432c-9ab4-946174c240c0"  # '0000-GA-Kontantstotte-Saksbehandler' - Saksbehandler
          - id: "52fe1bef-224f-49df-a40a-29f92d4520f8"  # '0000-GA-Kontantstotte-Beslutter' - Beslutter
          - id: "314fa714-f13c-4cdc-ac5c-e13ce08e241c"  # '0000-GA-Kontantstotte-Superbruker' - Superbruker
          - id: "c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b"  # teamfamilie-forvaltning
          - id: "e2cf416e-eb2b-4c86-8b5b-8c5b00385bcf"  # 0000-GA-ENHET_2103 (VIKAFOSSEN)
          - id: "16d14203-a5e0-4813-ba76-6d0a69aeb88b"  # 0000-GA-ENHET_4806 (DRAMMEN)
          - id: "a996c91f-6dd1-466d-bed0-06ddccab87f5"  # 0000-GA-ENHET_4820 (VADSØ)
          - id: "48ff353a-fd52-4109-be32-d0e825322b1f"  # 0000-GA-ENHET_4833 (OSLO)
          - id: "b00084c4-0325-4ec3-b17f-70aa0a03ed37"  # 0000-GA-ENHET_4842 (STORD)
          - id: "b5a21ebf-d8c7-415c-9a88-6b4735f845cd"  # 0000-GA-ENHET_4817 (STEINKJER)
          - id: "9a0b01fd-64ec-4912-8c32-d041417fc8ec"  # 0000-GA-ENHET_4863 (BERGEN)
          - id: "22a9b5f5-645f-4090-ae2d-29a38a126de6"  # 0000-GA-ENHET_4863 (MIDLERTIDIG_ENHET)
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ks-sak
  envFrom:
    - secret: familie-ks-sak-frontend
  env:
    - name: ENV
      value: preprod
  valkey:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: nodejs