apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://kontantstotte.intern.nav.no
  azure:
    application:
      enabled: true
      replyURLs:
        - https://kontantstotte.intern.nav.no/auth/openid/callback
      claims:
        groups:
          - id: "54cd86b8-2e23-48b2-8852-b05b5827bb0f"  # '0000-GA-Kontantstotte-Veileder' - Veileder
          - id: "e40090eb-c2fb-400e-b412-e9084019a73b"  # '0000-GA-Kontantstotte-Saksbehandler' - Saksbehandler
          - id: "4e7f23d9-5db1-45c0-acec-89c86a9ec678"  # '0000-GA-Kontantstotte-Beslutter' - Beslutter
          - id: "b8158d87-a284-4620-9bf9-f0aa3f62c8aa"  # '0000-GA-Kontantstotte-Superbruker' - Superbruker
          - id: "024bfb25-ead3-4c04-bbe1-1db3d3362188"  # teamfamilie-baks-forvaltning
          - id: "60102d01-2521-40b4-97b9-e2d738f642c1"  # 0000-GA-ENHET_2103 (VIKAFOSSEN)
          - id: "0d746128-7cb0-431b-9420-885e7a75260f"  # 0000-GA-ENHET_4806 (DRAMMEN)
          - id: "4a9058c7-daae-452a-9fea-23beaa0778ff"  # 0000-GA-ENHET_4820 (VADSØ)
          - id: "fde8342e-d9e6-4879-be17-a8f17cb9abfb"  # 0000-GA-ENHET_4833 (OSLO)
          - id: "4c0aff0d-78f9-4a4d-94d3-a31a28d75142"  # 0000-GA-ENHET_4842 (STORD)
          - id: "8672ac10-31f5-44df-b4a2-16d5443847bc"  # 0000-GA-ENHET_4817 (STEINKJER)
          - id: "4bfcd9dc-0290-4562-b352-6c56861a2dad"  # 0000-GA-ENHET_4812 (BERGEN)
          - id: "946a9fb3-1d6c-4cda-9bfe-aaa8b857dd1b"  # 0000-GA-ENHET_4863 (MIDLERTIDIG_ENHET)
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ks-sak
  envFrom:
    - secret: familie-ks-sak-frontend
  env:
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: ENV
      value: production
  valkey:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: nodejs