apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://kontantstotte.intern.nav.no
  azure:
    application:
      enabled: true
      replyURLs:
        - https://kontantstotte.intern.nav.no/auth/openid/callback
      claims:
        groups:
          - id: "54cd86b8-2e23-48b2-8852-b05b5827bb0f"  # '0000-GA-Kontantstotte-Veileder' - Veileder
          - id: "e40090eb-c2fb-400e-b412-e9084019a73b"  # '0000-GA-Kontantstotte-Saksbehandler' - Saksbehandler
          - id: "4e7f23d9-5db1-45c0-acec-89c86a9ec678"  # '0000-GA-Kontantstotte-Beslutter' - Beslutter
          - id: "b8158d87-a284-4620-9bf9-f0aa3f62c8aa"  # '0000-GA-Kontantstotte-Superbruker' - Superbruker
          - id: "3d718ae5-f25e-47a4-b4b3-084a97604c1d"  # teamfamilie-forvaltning
          - id: "833f1f77-b64b-4708-b479-389ca4009af5"  # MEDLEM: 2103 NAV Vikafossen
          - id: "c2cf4114-1f5d-47f2-bb6e-c7a06fd26412"  # MEDLEM: 4806 NAV Familie- og pensjonsytelser Drammen
          - id: "6c8c5d93-0e08-4bd8-960c-5c4c0ce5c609"  # MEDLEM: 4820 NAV Familie- og pensjonsytelser Vadsø
          - id: "9cd89ac3-5587-46ba-b571-a625f2af481d"  # MEDLEM: 4833 NAV Familie- og pensjonsytelser Oslo 1
          - id: "7af5f216-6a5e-4228-9c99-687658c5b957"  # MEDLEM: 4842 NAV Familie- og pensjonsytelser Stord
          - id: "0feaea21-ada1-48c0-9300-3f6aec36b993"  # MEDLEM: 4817 NAV Familie- og pensjonsytelser Steinkjer
          - id: "7342c168-80f4-4978-8a88-68cb43b85675"  # MEDLEM: 4812 NAV Familie- og pensjonsytelser Bergen
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ks-sak
  envFrom:
    - secret: ks-sak-frontend
  env:
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: ENV
      value: production
  valkey:
    - instance: sessions
      access: readwrite
    - instance: lookup
      access: read
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs