apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-sak-frontend
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://ks.dev.intern.nav.no
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - https://ks.dev.intern.nav.no/auth/openid/callback
      claims:
        groups:
          - id: "71f503a2-c28f-4394-a05a-8da263ceca4a"  # '0000-GA-Kontantstotte-Veileder' - Veileder
          - id: "c7e0b108-7ae6-432c-9ab4-946174c240c0"  # '0000-GA-Kontantstotte' - Saksbehandler
          # - id: "9449c153-5a1e-44a7-84c6-7cc7a8867233"  # BESLUTTER_ROLLE
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: familie-ks-sak
        - application: familie-ks-sak-frontend-redis
  envFrom:
    - secret: ks-sak-frontend
  env:
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: ENV
      value: preprod