# Full pipeline on push to main. Build, test, and deploy to dev + prod
name: Main
on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'main'
#    paths-ignore:
#      - '**.md'
#      - '**.MD'
#      - '.github/*.yml'
#      - '.husky/**'
#      - '.gitignore'
#      - '.prettierignore'
#      - '.prettierrc'
#      - 'CODEOWNERS'
#      - 'LICENSE'
#      - eslint.config.mjs

jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/build-yarn-app.yml@main
    with:
      build-image: true
      push-image: true
    secrets: inherit
  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    needs: [ build ]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yml@main
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: dev-gcp
      resource: build_n_deploy/naiserator/gcp-dev.yaml
    secrets: inherit
  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    needs: [ build, deploy-dev ]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/deploy.yml@main
    with:
      image: ${{ needs.build.outputs.image }}
      cluster: prod-gcp
      resource: build_n_deploy/naiserator/prod-dev.yaml
    secrets: inherit
